name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.0.5

      - name: Install Dependencies
        run: |
          R "-e install.packages('shiny')"
          R "-e devtools::install_github('jinworks/CellChat')"
      - name: Deploy Shiny App
        run: |
          R "-e shiny::runApp('app.R', port = 5825, host = '0.0.0.0')"
